---

- hosts: all
  become: true
  tasks:


  - name: update chache,install apache2 package and PHP packages for ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: absent
      update_cache: yes
    when: ansible_distribution == "Ubuntu"



  - name: update chache,install httpd package and PHP packages for Redhat
    yum:
      name: 
        - httpd
        - php
      state: absent
      update_cache: yes
    when: ansible_distribution == "RedHat"







