---

- hosts: all
  become: true
  tasks:


  - name: update chache,install apache package and PHP packages for ubuntu
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
    

