---

- hosts: all
  become: true
  pre_tasks:


  - name: install updates (Redhat)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"

  
  - name: install updates (Ubunutu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"





- hosts: web_servers
  become: true
  tasks:


  - name: update chache,install apache2 package and PHP packages for ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"



  - name: update chache,install httpd package and PHP packages for Redhat
    tags: apache,redhat,httpd
    yum:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "RedHat"


- hosts: db_servers
  become: true
  tasks:
  - name: install mariaDB package (RedHat)
    tags: redhat,db,mariadb
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "RedHat"

  
  - name: install mariaDb package (Ubuntu)
    tags: ubuntu,db,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_server
  become: true
  tasks:
  
  - name: install samba package
    tags: samba 
    package:
      name: samba
      state: latest



