- name: update chache,install apache2 package and PHP packages for ubuntu
  tags: apache,apache2,ubuntu
  apt:
    name: 
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"



- name: update chache,install httpd package and PHP packages for Redhat
  tags: apache,redhat,httpd
  yum:
    name: 
      - httpd
      - php
    state: latest
  when: ansible_distribution == "RedHat"



- name: start httpd (Redhat)
  tags: apache,centos,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "RedHat"




- name: change admin email address
  tags: apache,redhat,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin kninja@gmail.com
  when: ansible_distribution == "RedHat"
  register: httpd




- name: restart httpd (RedHat)
  tags: apache,redhat,httpd
  service:
    name: httpd
    state: restarted
  when: httpd.changed



- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644


